name: delta_to_html
version: 0.2.2

description: This lightweight package helps you convert Delta to HTML. HTML Most tags are supported in this package.
homepage: https://github.com/secanonm/delta_to_html

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0