name: delta_to_html
version: 0.1.6

description: This library helps you to convert Delta to HTML. Based on Flutter_Quill Delta 
homepage: https://github.com/secanonm/delta_to_html

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_quill: ^5.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0